### ISSUE TITLE
FY24 Q2 Release - using "Libraries" instead of databases

### ISSUE THREAD

**Issue by bkuczenski** [uslci-admin/private-uslci-content#14]
I noticed that beginning with FY24 Q2, the USLCI versions are archived as a "Library" instead of a database. There doesn't seem to be any notification or discussion about this. The only upshot that I can see is that flow properties and unit groups are no longer included in the archive. This is a (negligible) savings of space but has the downside that the archive is no longer complete (i.e. flows contain flow properties that are not included in the archive).

Opening this issue to hear a justification for the decision and consider possibly going back to the old way

**Comment by pweiler22** [comment]
The Federal LCA Commons/ Green Delta implemented libraries as a way to improve the interoperability of repositories on the Commons. With libraries we are able to prepare combined/mapped repositories; this process previously needed to be done by the users and was complicated. Use cases of libraries being beneficial include integrating the Electricity Baseline repository as a library into other repositories such as USLCI that may have older electricity grids. We are still working on improving the libraries feature so changes will be coming and suggestions are always welcomed. Changes that affect USLCI will be recorded on the press release and change log pages. We added some more details about this change to the most recent press releases -

"As a reminder, in Q2 2024 the USLCI curation team introduced the FLCAC Electricity Baseline repository as a library to the USLCI database to enhance the quality of electricity processes for background data use.

The version of the Electricity Baseline that is currently a library in USLCI has been adapted from the [public version of the repository](https://www.lcacommons.gov/lca-collaboration/Federal_LCA_Commons/US_electricity_baseline/datasets). Documentation on this adaptation is provided [here](https://github.com/FLCAC-admin/uslci-content/blob/dev/docs/supporting_docs/eLCI%20Library%20Change%20Log.md). The database from which the library has been generated from can be downloaded [here](https://github.com/FLCAC-admin/uslci-content/blob/dev/downloads/elci_6_2024%20for%20uslci_2024_final_database_format.zip)."
