### ISSUE TITLE
Empty elci zip files

### ISSUE THREAD

**Issue by deanmalmgren** [uslci-admin/private-uslci-content#18]
The zip files that are currently uploaded for elci appear to be empty. Is this intentional?

- https://github.com/FLCAC-admin/uslci-content/blob/refs/heads/dev/downloads/elci_6_2024%20for%20uslci_q2_2024_final_library%20format.zip
- https://github.com/FLCAC-admin/uslci-content/blob/refs/heads/dev/downloads/elci_6_2024%20for%20uslci_database%20format.zip

**Comment by pweiler22** [comment]
Thanks for pointing this problem out. The files have been reuploaded and are located here:
https://github.com/FLCAC-admin/uslci-content/blob/dev/downloads/elci_6_2024%20for%20uslci_2024_final_database_format.zip
https://github.com/FLCAC-admin/uslci-content/blob/dev/downloads/elci_6_2024%20for%20uslci_2024_final_library_format.zip

**Comment by deanmalmgren** [comment]
Amazing, thank you
