### ISSUE TITLE
Description Field Missing in FY2018 datasets

### ISSUE THREAD

**Issue by ezrakahn** [uslci-admin/private-uslci-content#2]
In all versions of the FY18 USLCI, the description field for the NETL coal data has gone missing.  It is present in the FY17 datasets.

@uslci-admin @acarpent @rferaldi

**Comment by acarpent** [comment]
this is weird. We have not been doing any work on those datasets. I know that Zac did some general updates prior to leaving, but don't know why he would do anything with the coal data.

@ezrakahn @rferaldi @uslci-admin

**Comment by FLCAC-admin** [comment]
I have not done anything with the coal data either...not sure why this would be occurring...

@ezrakahn @rferaldi @uslci-admin @acarpent

**Comment by ezrakahn** [comment]
There was a commit in april. What types of changes were committed at that point?

**Comment by FLCAC-admin** [comment]
@ezrakahn @acarpent @rferaldi 

I (Rebe as 'admin') made several commits in April:

* Added the example image I was able to attach to a JSON-LD file in oLCA to the development folder: https://github.com/uslci-admin/uslci-content/tree/dev/development

* Added 2018 versions of the USLCI db to the downloads folder (but 2017 ones are also still there): https://github.com/uslci-admin/uslci-content/tree/dev/downloads

  The 2018 versions of the USLCI db are what Zac had on file with the latest ERG polymer dataset additions. I did not modify them...just copied the files from the admin repository to make them available in the content repository.

* Added NREL's updated version of the Submission Handbook: https://github.com/uslci-admin/uslci-content/tree/dev/docs/submission_handbook

**Comment by ezrakahn** [comment]
This appears to go back to the zac days.  The descriptions are present in the Dec 28th version of the USLCI on the downloads file.  They are also present on the web version of the lcacommons.gov uslci.

they are NOT present on any of the file versions from after 2018.

I will basically start with the Dec 2017 uslci, merge with the 2018, which will leave about 6 - 8 things to copy and paste to update the kodak and eps resin

**Comment by ezrakahn** [comment]
commited the Dec 28 version, the re-commited the EPS resin data.  Things look correct now.
