### ISSUE TITLE
Cannot perform Monte Carlo Simulations

### ISSUE THREAD

**Issue by mrmayn** [uslci-admin/private-uslci-content#20]
Hello,
There seems to be some issue in USLCI which prevents performing a Monte Carlo (MC) Simulation. In the "Calculation properties" window, I can perform Lazy and Eager calculations just fine, but the MC Simulation option is grey and cannot be selected.

The problem seems unique to the USLCI data. When I create a "toy" process (elementary flows in, elementary flows out), the MC Simulation option is available. Connecting other "toy" product flows and processes works fine, too. Once I connect a product flow and designate a provider from USLCI, however, the MC Simulation option goes away.

I notice [in the FLCAC documentation for Running LCIA Results](https://flcac-admin.github.io/FLCAC-docs/running-lcia-results) that the sample screenshot in Step 10 shows the same grey MC Simulation option.

Is there any way to enable MC Simulations in USLCI at this time? If so, how can this be done?

On a related note (I can cross-post to the documentation Issues if needed), could information about this issue be added to the documentation? Either 1) a Note explaining how to enable MC Simulation of 2) a Note that MC Simulation is unavailable at this time.

Thanks.

**Comment by bnjmnmorelli** [comment]
@pweilerERG I experience the same lack of functionality for USLCI relative to other repos. Any ideas what could cause this?

Many of the processes in USLCI have no uncertainty data. So I tried adding uncertainty data to my product system and the still the monte carlo option was greyed out.

**Comment by bl-young** [comment]
We will look into this. I wonder if it has something to do with the electricity baseline library.

**Comment by pweiler22** [comment]
Yes, I think it is due to libraries. It is occurring regardless of whether precalculated matrices are used to generate the libraries. @SebastianGreve-GreenDelta do libraries objects in a product system prevent monte carlo simulations from being performed?

**Comment by mrmayn** [comment]
Thanks for looking into this - I just tested with releases Q2_2024 and Q1_2024. MC Simulation worked in Q1 but not Q2. Notably, Q1 also had the ecoinvent and ILCD data quality systems included in the zolca, but Q2 did not.

So on the user-side, this seems like a validation that it has to do with library implementation starting in Q2_2024.

**Comment by francoislerall** [comment]
Hi everyone,
Unfortunately, the Monte Carlo simulation is not available when using libraries at the moment. We are currently working on it and hope to include it in upcoming releases.

**Comment by mrmayn** [comment]
Closing since this is an OpenLCA-side issue they are currently working on. Thanks all!
