### ISSUE TITLE
Uncertainty information misaligned for `Wood Combusted, at boiler, at cellulosic fiberboard mill`

### ISSUE THREAD

**Issue by bl-young** [uslci-admin/private-uslci-content#21]
I just happened to notice that the min and max don't align with the stated value for these flows:

[Wood Combusted, at boiler, at cellulosic fiberboard mill](https://www.lcacommons.gov/lca-collaboration/National_Renewable_Energy_Laboratory/USLCI_Database_Public/dataset/PROCESS/106bcee8-0d5f-30c6-ac98-fa6dab41d4d1)

Identified in v.1.2014-10.0

![image](https://github.com/user-attachments/assets/7ad1035a-1e3e-482f-9b16-3aebdb499bce)

**Comment by pweiler22** [comment]
fixed, reset the max values to be the amount for each flow in this inventory that had uncertainty defined
