### ISSUE TITLE
Broken exchange for `Electricity, natural gas, at power plant`

### ISSUE THREAD

**Issue by bl-young** [uslci-admin/private-uslci-content#22]
Appears to be caused by a units mismatch, e.g.:
![image](https://github.com/user-attachments/assets/5cca23b7-05fb-4d46-820f-47cc886fbe21)

While the version on the commons shows MJ for that specific flow:
![image](https://github.com/user-attachments/assets/0a8fbe6b-c24d-4e71-8a7e-f9294420519f)

**Processes effected:**
Data set | UUID
-- | --
Electricity, Western US, 2014 - US | 7d66e309-5774-4aea-88ce-56868c6f54a7
Electricity, bauxite mining regions - GLO | 6023a2bf-2d42-348b-bee7-caae15319edb
Electricity, alumina refining regions -   RNA | a6260670-e98e-3917-98bd-c14acb79fdf7
Electricity, aluminum smelting and ingot   casting regions - RNA | 4d21df14-9a73-31ce-9a5f-dee0cd2a2aed
Electricity, at Grid, US, 2010 - RNA | 89389d98-1ba6-30c5-9c33-92443694936b
Electricity, at grid, CN, 2018 - CN | ab7f18b8-9e1b-4efc-a690-5d9ffe6e0cc1
Electricity, Eastern US, 2014 - US | e5856077-a966-4692-9d10-e747237d4fa6
Wood Combusted, at boiler, at cellulosic   fiberboard mill - RNA | 106bcee8-0d5f-30c6-ac98-fa6dab41d4d1
Electricity, at cogen, for natural gas   turbine - PY | e6586e69-95a4-3396-a934-f379fbdd28f4
Cellulosic fiberboard, uncoated, at plant   - RNA | cced9535-72f6-3b3a-b3c0-ce21b98eea2b
Hardboard, at hardboard plant - RNA | ca1d1dfa-fd3c-35f1-bea7-a037251deb04

![image](https://github.com/user-attachments/assets/be768c25-b5bd-4d93-ad07-5b3c748bd1bd)

**Comment by bl-young** [comment]
Replacing the broken exchange seems to resolve the issue and the validation errors go away.

**Comment by bl-young** [comment]
Fixed in CS commit e278b59e9af0940b791064d4c7a7fc8982b87836.

Except for `Electricity, at cogen, for natural gas turbine - PY` for which units need to be confirmed.

**Comment by bl-young** [comment]
@pweilerERG could you take a look at this cogen process:
![image](https://github.com/user-attachments/assets/9cd3b1d5-55d6-4d42-acf9-70c198e4a579)

I'm not sure the history of it, but currently the units are wrong. By my read I think the value should be 2 kWh (3.6 MJ), but I also wanted to confirm that this should be an input of electricity and not the NG itself. I didn't fix the broken exchange for this process yet.

**Comment by pweiler22** [comment]
Need to investigate what is causing the mismatch in units and broken exchanges... why are these popping up after weeks/months on the collab server but not during release QA/QC?

**Comment by pweiler22** [comment]
Corrected this, the input flow and units were incorrect. Should have been 0.1875 m3 nat gas, combusted in industrial boiler
