### ISSUE TITLE
Drop old electricity processes (e.g., `Electricity, Eastern US, 2014`)

### ISSUE THREAD

**Issue by bl-young** [uslci-admin/private-uslci-content#23]
Coal and Nuclear appear to be missing.

[Electricity, Eastern US, 2014](https://www.lcacommons.gov/lca-collaboration/National_Renewable_Energy_Laboratory/USLCI_Database_Public/dataset/PROCESS/e5856077-a966-4692-9d10-e747237d4fa6)

Compare to [Western, US.](https://www.lcacommons.gov/lca-collaboration/National_Renewable_Energy_Laboratory/USLCI_Database_Public/dataset/PROCESS/7d66e309-5774-4aea-88ce-56868c6f54a7?commitId=c53aed355741a068d615f1a7674a2c6218ce98dd).

The total sum of inputs is much less than 1.

**Comment by FLCAC-admin** [comment]
These processes aren't being used anymore and were missed when we were phasing out electricity processes that are not used when integrating elci. Let's delete these, unless you have any objections.

**Comment by pweiler22** [comment]
These processes aren't being used anymore and were missed when we were phasing out electricity processes that are not used when integrating elci. Let's delete these, unless you have any objections.

**Comment by bl-young** [comment]
ok, no I think that's fine. Would this apply to `Electricity, at Grid, US, 2010 - RNA` as well?

Each of these also has a unique technosphere flow that are not being consumed anywhere.

**Comment by bl-young** [comment]
These were dropped in CS commit 1bad2062f3fb9ac851b72c761f9e1b0eeb0c29ec
