### ISSUE TITLE
Replace `Elementary Flows` folder with `Elementary flows`

### ISSUE THREAD

**Issue by bl-young** [uslci-admin/private-uslci-content#34]
This would be consistent with other repositories.

And also `Technosphere Flows` to `Technosphere flows` for consistency.

**Comment by bnjmnmorelli** [comment]
no concerns on my end.

**Comment by bl-young** [comment]
Elementary flows updated in CS commit Fixed in CS commit 3ba8842068bae0cd99d3d745058250cf9e8cca7b.

Technosphere flows moved to new issue
