### ISSUE TITLE
Replace Manganese-55 flow in Polyol ether, for rigid foam polyurethane production, at plant

### ISSUE THREAD

**Issue by bl-young** [uslci-admin/private-uslci-content#39]
If this flow gets replaced in the FEDEFL (see https://github.com/USEPA/fedelemflowlist/issues/211), this single exchange will need to be revised with the new flow.

**Comment by bl-young** [comment]
There is no kbq conversion for this flow so recommend just dropping this exchange (emission to water)

**Comment by pweiler22** [comment]
So I'll delete that exchange and the flow?

**Comment by bl-young** [comment]
yes, it doesn't really make sense and we don't have a kbq to kg conversion for it.
