### ISSUE TITLE
US LCI database in a matrix format? 

### ISSUE THREAD

**Issue by xliao2010** [uslci-admin/private-uslci-content#4]
Hi, 

Is it possible to provide the USLCI in the simple matrix format (in csv or excel), similar to the SimaPro matrix export, to make computation easier on the database level? It should include the basic items, i.e., techno-matrix A, intervention matrix B, and product vector f, compartment, sub-compartment, unit? 

Thanks. 
XL

**Comment by FLCAC-admin** [comment]
Importing the USLCI Database (e.g., in JSON-LD format) into the openLCA software allows the user to export the selected process (or all database processes at once) into Excel files simply by right-clicking on the database, selecting export, and then selecting the Excel file format. There will be one spreadsheet for each exported process with the following tabs: General Information, Inputs, Outputs, Parameters, Allocation, Modeling and validation, Administrative information, Flows, Flow property factors, Units, Unit groups, Flow properties, Actors, Sources, and Locations.

**Comment by FLCAC-admin** [comment]
@xliao2010 : has your issue been resolved?
