### ISSUE TITLE
Can the Ecospold version be imported into SimaPro directly?

### ISSUE THREAD

**Issue by xliao2010** [uslci-admin/private-uslci-content#5]
Hello,

Is it possible to import the ecospold version directly into the SimaPro? Is there a corresponding mapping file? 

https://github.com/uslci-admin/uslci-content/blob/dev/downloads/uslci_fy20_q2_01_olca1_10_3_ecospold2.zip

Thanks,
Xun

**Comment by FLCAC-admin** [comment]
USLCI admin does not have access to a SimaPRO license to determine if a mapping file is required or to create an associated mapping file. I am contacting Long Trail (ITexperts) to inquire. I will post their feedback here.

**Comment by uslci-admin** [comment]
@xliao2010 : I am still waiting on Pre to respond to my inquiries. However, NREL did receive the following notice regarding the publishing of DataSMART 2020 has been published: 

The DATASMART 2020 Update is now available! | The DATASMART 2020 Update is now available!
-- | --
The DATASMART 2020 Update is now available!
The DATASMART 2020 Update includes 11 new processes, 75 updated processes, and 11 corrected processes. This includes new molybdenum data from the International Molybdenum Association. Electricity mixes for Canadian provinces and territories, the Canadian country average, U.S. eGRID, U.S. state and the U.S. country average were also updated to incorporate the most recently published data. Two new waste scenarios for general waste and packaging waste were created based on the most recent publications from the U.S. Environmental Protection Agency. The LTS Method was updated with the latest ReCiPe 2016 version 1.04 method. Finally, corrected water flows were corrected for Chinese textile processing system level data. Learn more about these updates in a free webinar on November 18th from noon-1pm ET. Email us at info@ltsexperts.com to register. | The DATASMART 2020 Update includes 11 new processes, 75 updated processes, and 11 corrected processes. This includes new molybdenum data from the International Molybdenum Association. Electricity mixes for Canadian provinces and territories, the Canadian country average, U.S. eGRID, U.S. state and the U.S. country average were also updated to incorporate the most recently published data. Two new waste scenarios for general waste and packaging waste were created based on the most recent publications from the U.S. Environmental Protection Agency. The LTS Method was updated with the latest ReCiPe 2016 version 1.04 method. Finally, corrected water flows were corrected for Chinese textile processing system level data. Learn more about these updates in a free webinar on November 18th from noon-1pm ET. Email us at info@ltsexperts.com to register.

The DATASMART 2020 Update includes 11 new processes, 75 updated processes, and 11 corrected processes. This includes new molybdenum data from the International Molybdenum Association. Electricity mixes for Canadian provinces and territories, the Canadian country average, U.S. eGRID, U.S. state and the U.S. country average were also updated to incorporate the most recently published data. Two new waste scenarios for general waste and packaging waste were created based on the most recent publications from the U.S. Environmental Protection Agency. The LTS Method was updated with the latest ReCiPe 2016 version 1.04 method. Finally, corrected water flows were corrected for Chinese textile processing system level data. Learn more about these updates in a free webinar on November 18th from noon-1pm ET. Email us at info@ltsexperts.com to register.

Update Now | Update Now
Update Now
The DATASMART 2020 update is now available for you to download! Please find your credentials and instructions below, and the DATAMSART What's New, update/installation manual and manual attached.  1.    Log-on to our website at http://ltsexperts.com/wp-admin        User name: NREL        Password: z&8391fTrC(uZ@0t*6gqsZk%2. Then go to https://ltsexperts.com/download/datasmart-download/3. Next, enter LTS2020DS for the password to the right of "DATASMART2020" and click the green download button.4. Follow the instructions attached to restore the DATASMART SimaPro backup file and import INTO your database. | The DATASMART 2020 update is now available for you to download! Please find your credentials and instructions below, and the DATAMSART What's New, update/installation manual and manual attached.  1.    Log-on to our website at http://ltsexperts.com/wp-admin        User name: NREL        Password: z&8391fTrC(uZ@0t*6gqsZk%2. Then go to https://ltsexperts.com/download/datasmart-download/3. Next, enter LTS2020DS for the password to the right of "DATASMART2020" and click the green download button.4. Follow the instructions attached to restore the DATASMART SimaPro backup file and import INTO your database.

The DATASMART 2020 update is now available for you to download! Please find your credentials and instructions below, and the DATAMSART What's New, update/installation manual and manual attached.  1.    Log-on to our website at http://ltsexperts.com/wp-admin        User name: NREL        Password: z&8391fTrC(uZ@0t*6gqsZk%2. Then go to https://ltsexperts.com/download/datasmart-download/3. Next, enter LTS2020DS for the password to the right of "DATASMART2020" and click the green download button.4. Follow the instructions attached to restore the DATASMART SimaPro backup file and import INTO your database.

Submit Data | Submit Data
Submit Data

Are you interested in having your data in DATASMART?You can choose to publish your data at the unit or system level (we will need to review the unit level), and have the option to be listed as the generator (or not!). Follow these procedures to get started. Please email us at info@ltsexperts.com if you have any questions.  Long Trail Sustainability \| 802-434-3326 \| info@ltsexperts.comhttps://ltsexperts.com/ | Are you interested in having your data in DATASMART?You can choose to publish your data at the unit or system level (we will need to review the unit level), and have the option to be listed as the generator (or not!). Follow these procedures to get started. Please email us at info@ltsexperts.com if you have any questions.  Long Trail Sustainability \| 802-434-3326 \| info@ltsexperts.com https://ltsexperts.com/

Are you interested in having your data in DATASMART?You can choose to publish your data at the unit or system level (we will need to review the unit level), and have the option to be listed as the generator (or not!). Follow these procedures to get started. Please email us at info@ltsexperts.com if you have any questions.  Long Trail Sustainability \| 802-434-3326 \| info@ltsexperts.comhttps://ltsexperts.com/

**Comment by FLCAC-admin** [comment]
After discussion with Pre, the developers of SimaPRO, I understand that special mapping files ARE required to import the current, FEDEFL-adapted version of the USLCI directly into SimaPRO. Pre intends to facilitate updating SimaPRO for this capacity in the coming year. Also, the GLAD nomenclature working group is currently working on bi-directional mapping harmonization for 4 key flow lists (ILCD, ecoinvent, IDEA, FEDEFL); see this [GLAD progress article](https://www.lifecycleinitiative.org/glad-progresses-but-much-more-still-to-do/?utm_source=rss&utm_medium=rss&utm_campaign=glad-progresses-but-much-more-still-to-do). Having the GLAD bi-directional mappings may accelerate the adaptation of the FEDEFL, and thus, updated USLCI into SimaPRO.
